name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: 'true'

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            10.0.x
            11.0.x
          include-prerelease: true

      - name: Check Building ⚙
        run: |
          dotnet restore AntDesign.Icons.sln
          dotnet build AntDesign.Icons.sln --configuration Release --no-restore
